# Generated by Django 2.2.5 on 2019-10-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20191009_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('blocked', 'Заблокирован')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
