# Generated by Django 2.2.5 on 2019-10-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
