# Generated by Django 2.2.5 on 2019-11-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20191105_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'permissions': [('can_add_issue_for_project', 'Может добавлять задачи к проекту')], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
